### ISSUE TITLE
请问我这样设置是运行成功了？

### ISSUE THREAD

**Issue by Heiwk** [Guovin/TV#444]
请问一下博主，我这样算是运行成功了？为什么一直在这个地方没有进一步的动静了。图片是我自己设置的
环境飞牛os系统的docker下面容器自己设定了， ​/vol1/1000/docker/config   /vol1/1000/docker/output  这2个是我的路径
也不知道程序正常工作了吗，查看运行日志一直就那几条记录也不知道到什么时候回下一步。
那个进度日志我看了就是这个样没有别的代码流程出现了。请问后续会增加docker 可视化扫描或者程序完成的进度条显示？让我们更加
直观的看到进行到哪一步。还有多久完成任务。感谢博主希望能指导一下谢谢你
路径
![4匪徒](https://github.com/user-attachments/assets/3f771ba8-ad79-4c61-922f-a7048cc34a1f)
![111](https://github.com/user-attachments/assets/0eaa6eb3-d49b-4be8-b7b8-3d11f32706e3)
![234](https://github.com/user-attachments/assets/5672a140-bd09-4d01-9eb5-85803008c78f)
![567](https://github.com/user-attachments/assets/4ae38001-c821-4430-b715-d0fe8c043dab)
![789](https://github.com/user-attachments/assets/e35253b2-9c23-4fe9-88e9-71c35cd061d5)

**Comment by Guovin** [comment]
有尝试过重启容器吗？

**Comment by Heiwk** [comment]
> 有尝试过重启容器吗？

我手动点停止又重启了还是停留这里无法继续下去。这个现在我停止出来的。然后又重启一次了。时间很久了发现还停留在此处。所以我也不知道运行失败还是卡机了。
![12121](https://github.com/user-attachments/assets/c1645d01-35e0-4de3-bab4-602561b72ff8)
重启后这样的画面，
![3445](https://github.com/user-attachments/assets/32fbb99b-f908-4b68-8b65-6cf0b870cfa4)
点开output里面只有一个空白的log什么没有出现了11:44重启了。我是手动点了启动没有通过命令启动
![32](https://github.com/user-attachments/assets/1142ba78-8e35-42a7-a96e-74902d125ff7)

**Comment by Heiwk** [comment]
> 有尝试过重启容器吗？
同样差不多一起开始 了更新工具更新很流畅的在运行。。这个docker 更新的进度一直不在变化
![898](https://github.com/user-attachments/assets/08e08904-65b5-4eb8-bef1-781bf4ed5cb0)

**Comment by Guovin** [comment]
docker容器日志输出有延迟，试试等一会看看

**Comment by Heiwk** [comment]
饭饭吃过了还是这样。请问我的路径是对的嘛？还是由于我设置路径错误导致程序卡bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Guovin/TV] 请问我这样设置是运行成功了？ (Issue #444)




 
docker容器日志输出有延迟，试试等一会看看

**Comment by Heiwk** [comment]
> docker容器日志输出有延迟，试试等一会看看

工具都更新好了，docker还在那个界面不动一点。。。。

**Comment by Guovin** [comment]
我观察了下，日志有概率会卡在那里，但实际流程是一直在走的，等待片刻后就有日志输出了，默认配置一般半个小时内就更新完成了。你是不是改过默认模板添加了一些频道，或修改过配置？导致更新时间比较长

**Comment by Ghostpanter** [comment]
这是fnos吧，我用着没啥问题，我的docker-compose.yaml这么写的
```yaml
version: '3.8'

services:
  tv-requests:
    image: registry.cn-hangzhou.aliyuncs.com/kkun/tv-requests
    ports:
      - "9095:8000"
    volumes:
      - /vol1/1000/container/TV/config:/tv-requests/config
      - /vol1/1000/container/TV/output:/tv-requests/output
      - TZ=Asia/Shanghai
    restart: always
```
